Turismo_Real/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include ('Turismo_core.urls')),
    path('accounts/', include ('django.contrib.auth.urls'))
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Turismo_core/urls.py
from django.urls import path
from .views import *

urlpatterns = [
	path('', home,name="home"),
	#Registrar Usuarios
	path('agregar_cliente/', agregar_cliente, name="agregar_cliente"),
	path('listar_clientes/', listar_clientes, name="listar_clientes"),
	path('modificar_cliente/<run>/', modificar_cliente, name="modificar_cliente"),
	path('eliminar_cliente/<run>/', eliminar_cliente, name="eliminar_cliente"),
	#Departamentos
	path('agregar_departamento/', agregar_departamento, name="agregar_departamento"),
	path('listar_departamentos/', listar_departamentos, name="listar_departamentos"),
	path('modificar_departamento/<cod_depa>/', modificar_departamento, name="modificar_departamento"),
	path('eliminar_departamento/<cod_depa>/', eliminar_departamento, name="eliminar_departamento"),
	#Usuarios-Django
	path('registro/', registro, name="registro"),
	#reservas
	path('agregar_reserva/', agregar_reserva, name="agregar_reserva"),
	path('listar_reservas/', listar_reservas, name="listar_reservas"),
	path('modificar_reserva/<cod_reserva>/', modificar_reserva, name="modificar_reserva"),
	path('eliminar_reserva/<cod_reserva>/', eliminar_reserva, name="eliminar_reserva"),
	#inventario
	path('agregar_inventario/', agregar_inventario, name="agregar_inventario"),
	path('listar_inventarios/', listar_inventarios, name="listar_inventarios"),
	path('modificar_inventario/<cod_inventario>/', modificar_inventario, name="modificar_inventario"),
	path('eliminar_inventario/<cod_inventario>/', eliminar_inventario, name="eliminar_inventario"),

]

Turismo_core/models.py
# Create your models here.
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class AuthGroup(models.Model):
    name = models.CharField(unique=True, max_length=150, blank=True, null=True)

    

class AuthGroupPermissions(models.Model):
    id = models.BigAutoField(primary_key=True)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)
    permission = models.ForeignKey('AuthPermission', models.DO_NOTHING)


class AuthPermission(models.Model):
    name = models.CharField(max_length=255, blank=True, null=True)
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING)
    codename = models.CharField(max_length=100, blank=True, null=True)

 


class AuthUser(models.Model):
    password = models.CharField(max_length=128, blank=True, null=True)
    last_login = models.DateTimeField(blank=True, null=True)
    is_superuser = models.BooleanField()
    username = models.CharField(unique=True, max_length=150, blank=True, null=True)
    first_name = models.CharField(max_length=150, blank=True, null=True)
    last_name = models.CharField(max_length=150, blank=True, null=True)
    email = models.CharField(max_length=254, blank=True, null=True)
    is_staff = models.BooleanField()
    is_active = models.BooleanField()
    date_joined = models.DateTimeField()


class AuthUserGroups(models.Model):
    id = models.BigAutoField(primary_key=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)

class AuthUserUserPermissions(models.Model):
    id = models.BigAutoField(primary_key=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    permission = models.ForeignKey(AuthPermission, models.DO_NOTHING)


class CheckInv1(models.Model):
    cod_chek_in = models.CharField(primary_key=True, max_length=60)
    horario = models.DateField()
    documento = models.BinaryField()

    def __str__(self):
    	return self.cod_chek_in



class CheckOut(models.Model):
    cod_check_out = models.CharField(primary_key=True, max_length=6)
    horario = models.DateField()
    documento = models.BinaryField()
    multa = models.BigIntegerField(blank=True, null=True)
    multa_1 = models.BigIntegerField(blank=True, null=True)

    def __str__(self):
    	return self.cod_check_out

 

class Conductor(models.Model):
    cod_conductor = models.CharField(primary_key=True, max_length=6)
    run = models.IntegerField()
    nombre = models.CharField(max_length=15)
    apellido_p = models.CharField(max_length=15)
    apellido_m = models.CharField(max_length=15)
    tipo_licencia = models.CharField(max_length=10)
    cod_transporte = models.CharField(unique=True, max_length=6)
    dv = models.CharField(max_length=1)
    imagen = models.ImageField(upload_to="Conductores", null=True)

    def __str__(self):
    	return self.nombre

   

class Departamento(models.Model):
    cod_depa = models.CharField(primary_key=True, max_length=6)
    fotos = models.BinaryField()
    dormitorios = models.CharField(max_length=10)
    banos = models.CharField(max_length=10)
    tipo = models.CharField(max_length=20)
    valor_depa_xdia = models.BigIntegerField()
    evaluo_inv_total = models.BigIntegerField()
    imagen = models.ImageField(upload_to="Departamentos", null=True)
    mantenimiento_cod_mantenimiento = models.ForeignKey('Mantenimiento', models.DO_NOTHING, db_column='mantenimiento_cod_mantenimiento')
    inventario_cod_invetario = models.ForeignKey('Inventario', models.DO_NOTHING, db_column='inventario_cod__invetario')  # Field renamed because it contained more than one '_' in a row.

    def __str__(self):
    	return self.cod_depa

  
class DjangoAdminLog(models.Model):
    action_time = models.DateTimeField()
    object_id = models.TextField(blank=True, null=True)
    object_repr = models.CharField(max_length=200, blank=True, null=True)
    action_flag = models.IntegerField()
    change_message = models.TextField(blank=True, null=True)
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING, blank=True, null=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)

  
class DjangoContentType(models.Model):
    app_label = models.CharField(max_length=100, blank=True, null=True)
    model = models.CharField(max_length=100, blank=True, null=True)

   
class DjangoMigrations(models.Model):
    id = models.BigAutoField(primary_key=True)
    app = models.CharField(max_length=255, blank=True, null=True)
    name = models.CharField(max_length=255, blank=True, null=True)
    applied = models.DateTimeField()

  
class DjangoSession(models.Model):
    session_key = models.CharField(primary_key=True, max_length=40)
    session_data = models.TextField(blank=True, null=True)
    expire_date = models.DateTimeField()




class Inventario(models.Model):
    cod_inventario = models.CharField(primary_key=True, db_column='cod__inventario', unique=True, max_length=6)  # Field renamed because it contained more than one '_' in a row.
    nombre_obj = models.CharField(max_length=50)
    cantidad = models.BigIntegerField()
    estado_obj = models.CharField(max_length=50)
    cod_depa = models.CharField(primary_key=False, max_length=6)
    evaluo_obj = models.BigIntegerField()
    tipo_objeto = models.CharField(max_length=10, blank=True, null=True)

    def __str__(self):
    	return self.nombre_obj

  

class Mantenimiento(models.Model):
    cod_depa = models.CharField(unique=True, max_length=6)
    cod_mantenimiento = models.CharField(primary_key=True, max_length=6)
    reparacion = models.CharField(max_length=50)
    disponiblidad = models.CharField(max_length=2)
    mejora = models.CharField(max_length=50)
    limpieza = models.CharField(max_length=50)

    def __str__(self):
    	return self.cod_depa


class Reserva(models.Model):
    cod_reserva = models.CharField(primary_key=True, max_length=6)
    pago_parcial = models.BigIntegerField()
    tipo_reserva = models.CharField(max_length=50)
    pago_completo = models.BigIntegerField()
    pago_aprobado = models.BooleanField()
    departamento_cod_depa = models.ForeignKey(Departamento, models.DO_NOTHING, db_column='departamento_cod_depa')
    usuario_run = models.ForeignKey('Usuario', models.DO_NOTHING, db_column='usuario_run')
    check_inv2_cod_chek_in = models.ForeignKey(CheckInv1, models.DO_NOTHING, db_column='check_inv2_cod_chek_in',default="")
    check_out_cod_check_out = models.ForeignKey(CheckOut, models.DO_NOTHING, db_column='check_out_cod_check_out')

    def __str__(self):
    	return self.cod_reserva

  

class Servicios(models.Model):
    cod_serv = models.CharField(primary_key=True, max_length=6)
    transporte_cod_transporte = models.ForeignKey('Transporte', models.DO_NOTHING, db_column='transporte_cod_transporte')
    tour_cod_tour = models.ForeignKey('Tour', models.DO_NOTHING, db_column='tour_cod_tour')
    reserva_cod_reserva = models.ForeignKey(Reserva, models.DO_NOTHING, db_column='reserva_cod_reserva')

    def __str__(self):
    	return self.cod_serv

  
class Tour(models.Model):
    cod_tour = models.CharField(primary_key=True, max_length=6)
    horario = models.DateField()
    fecha = models.DateField()
    tipo_tour = models.CharField(max_length=10)

    def __str__(self):
    	return self.cod_tour


class Transporte(models.Model):
    cod_transporte = models.CharField(primary_key=True, max_length=6)
    lugar = models.CharField(max_length=50)
    horario = models.DateField()
    desde = models.CharField(max_length=50)
    hasta = models.CharField(max_length=50)
    vehiculo_cod_vehiculo1 = models.ForeignKey('Vehiculo', models.DO_NOTHING, db_column='vehiculo_cod_vehiculo1')
    conductor_cod_conductor = models.ForeignKey(Conductor, models.DO_NOTHING, db_column='conductor_cod_conductor')

    def __str__(self):
    	return self.cod_transporte

  

class Usuario(models.Model):
    run = models.CharField(primary_key=True, max_length=50)
    nombre = models.CharField(max_length=20)
    apellido_p = models.CharField(max_length=20)
    apellido_m = models.CharField(max_length=50)
    tipo_us = models.BooleanField()
    contrasena = models.CharField(max_length=16)
    correo = models.EmailField(default="asd@ad.cl")

    def __str__(self):
    	return self.nombre




class Vehiculo(models.Model):
    cod_vehiculo = models.CharField(max_length=6)
    tipo_vehiculo = models.CharField(max_length=15)
    marca = models.CharField(max_length=15)
    color = models.CharField(max_length=15)
    patente = models.CharField(max_length=6)
    cod_transporte = models.CharField(unique=True, max_length=6)
    cod_vehiculo2 = models.CharField(primary_key=True, max_length=6)

    def __str__(self):
    	return self.cod_vehiculo



class Zona(models.Model):
    direccion = models.CharField(max_length=50)
    ciudad = models.CharField(max_length=30)
    comuna = models.CharField(max_length=30)
    region = models.CharField(max_length=30)
    cod_zona = models.CharField(primary_key=True, max_length=6)

    def __str__(self):
    	return self.ciudad

   

Turismo_core/forms.py
from django import forms
from .models import *
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class UsuarioForm(forms.ModelForm):

	imagen = forms.ImageField(required=False)

	class Meta:
		model = Usuario
		fields = ["run", "nombre", "apellido_p", "apellido_m", "tipo_us", "contrasena", "correo"]
		#fields = '__all__'

class DepartamentoForm(forms.ModelForm):
	imagen = forms.ImageField(required=False)
	#mantenimiento_cod_mantenimiento = ForeignKey(required=False)
	#inventario_cod_invetario = ForeignKey(required=False)
	class Meta:
		model = Departamento
		fields = '__all__'

class CustomUserCreationForm(UserCreationForm):
	
	class Meta:
		model = User
		fields= ["username", "first_name", "last_name", "email", "password1", "password2"]

class ReservaForm(forms.ModelForm):

	class Meta:
		model = Reserva
		fields = '__all__'

class InventarioForm(forms.ModelForm):

	class Meta:
		model = Inventario
		fields = '__all__'

Turismo_core/templates/Turismo_core/Registrarse.html
{% extends 'Turismo_core/base.html'%}

	{% block carousel %}
		{% load static %}

		<form action="" class="formulario_registro" method="post">

			{% csrf_token %}
			{{ form }}
			<button type="submit" id="btnEnviar" class="button">Enviar</button>
		</form>
		{{mensaje}}

	{% endblock %}

Turismo_core/templates/Turismo_core/Reserva.html
{% extends 'Turismo_core/base.html'%}

{% block carousel %}
	{% load static %}

		
		<form action="" class="formulario_reserva" id = "formulario_reserva">
			<label for="nombre"> Nombre</label>
			<input type="text" id="Nombre" name="Nombre">

			<button type="button" id="btnEnviar" class="button">Enviar</button>

		</form>
	
	{% for d in departamentos %}
		<div class="Departamentos"> 

			<h2> Departamentos </h2>

			<h5>{{ d.cod_depa}}</h5>


		</div>

	{% endfor %}



{% endblock %}

Turismo_core/templates/Turismo_core/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<link rel="apple-touch-icon" sizes="76x76" href="{% static '/Turismo_core/assets/img/apple-icon.png' %}">
	<link rel="icon" type="image/png" href="{% static '/Turismo_core/assets/img/favicon.png' %}">	
	
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
	<title>DEPA Project</title>

	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />
	
    <link href="{% static '/Turismo_core/bootstrap3/css/bootstrap.css' %}" rel="stylesheet" />
	<link href="{% static '/Turismo_core/assets/css/gsdk.css' %}" rel="stylesheet" />  
    <link href="{% static '/Turismo_core/assets/css/demo.css' %}" rel="stylesheet" /> 
    
    <!--     Font Awesome     -->
    <link href="{% static '/Turismo_core/bootstrap3/css/font-awesome.css' %}" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Grand+Hotel' rel='stylesheet' type='text/css'>
</head>
<body>
  

<div id="navbar-full">
      <div id="navbar">
      <div class="navigation-example">
          <nav class="navbar navbar-default navbar-transparent" role="navigation-demo">
            <div class="container">
              <!-- Brand and toggle get grouped for better mobile display -->
              <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-example-2">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#gsdk">DEPA PROJECT</a>
              </div>
          
          <!-- Collect the nav links, forms, and other content for toggling -->
              <div class="collapse navbar-collapse" id="navigation-example-2">
                <ul class="nav navbar-nav">
                  <li class="active"><a href="#gsdk">Departamentos</a></li>
                  <li class="dropdown">
                        <a href="#gsdk" class="dropdown-toggle" data-toggle="dropdown">Menu <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                          <li><a href="#gsdk">Galería</a></li>
                          <li><a href="#gsdk">¿Quienes somos?</a></li>
                          <!-- CLIENTES -->
                          <li><a href="{% url 'agregar_cliente' %}">Registrarse (Feature en desarrollo)</a></li>
                          <li><a href="{% url 'listar_clientes' %}">Listar Clientes (Feature en desarrollo)</a></li>
                          <!-- RESERVAS -->
                          <li><a href="{% url 'agregar_reserva' %}">¡Agenda Online!</a></li>
                          {% if perms.Turismo_core.change_reserva %}
                          <li><a href="{% url 'listar_reservas' %}">Listar Pagos</a></li>
                          {% endif %}
                          <!-- DEPARTAMENTOS -->
                          {% if perms.Turismo_core.view_departamento %}
                          <li><a href="{% url 'listar_departamentos' %}">Lista de departamentos</a></li>
                          {% endif %}
                          {% if perms.Turismo_core.add_departamento %}
                          <li><a href="{% url 'agregar_departamento' %}">Agregar de departamento</a></li>
                          {% endif %}
                          <!-- INVENTARIOS -->
                          <li><a href="{% url 'agregar_inventario' %}">Agregar Inventario</a></li>
                          <li><a href="{% url 'listar_inventarios' %}">Listar Inventarios</a></li>
                          <li class="divider"></li>
                          <li><a href="#gsdk">Ubicaciones</a></li>
                          <!-- SESIONES -->
                          {% if user.is_authenticated %}
                          <li>
                            <a href="{% url 'logout' %}">Cerrar Sesion</a>
                          </li>
                          {% else %}
                          <li>
                            <a href="{% url 'login' %}">Iniciar Sesion</a>
                          </li>
                          <!-- REGISTRARSE EN DJANGO -->
                          <li>
                            <a href="{% url 'registro' %}">Registrate Ahora! (Oficial)</a>
                          </li>

                          {% endif %}
                        </ul>
                  </li>
                  <li>
                      <a href="javascript:void(0);" data-toggle="search" class="hidden-xs"><i class="fa fa-search"></i></a>
                  </li>
                </ul>
                <form class="navbar-form navbar-left navbar-search-form" role="search">                  
                  <div class="form-group">
                        <input type="text" value="" class="form-control" placeholder="Search...">
                  </div> 
                </form>
                <ul class="nav navbar-nav navbar-right">
                      <li><a href="#mundo">¡HOLA!</a></li>
                      
                      <li><a href="http://127.0.0.1:8000/admin/"  class="btn btn-round btn-default">{{ user.username }}</a></li>
                </ul>
                
              </div><!-- /.navbar-collapse -->

            </div><!-- /.container-fluid -->
          </nav>        
              <div class="img-src" style="background-image: url({% static '/Turismo_core/assets/img/bg.jpg' %})"></div>
          </div>
      </div><!--  end navbar -->

</div>

<div>
</div>
        

<div id="carousel">
    <!--    
            IMPORTANT - This carousel can have a special class for a smooth transition "gsdk-transition". Since javascript cannot be overwritten, if you want to use it, you can use the bootstrap.js or bootstrap.min.js from the GSDKit or you can open your bootstrap.js file, search for "emulateTransitionEnd(600)" and change it with "emulateTransitionEnd(1200)"     
            
    -->
    {% if messages %}

      {% for m in messages %}
          
        {{m}}

      {% endfor %}

    {% endif %}

    {% block carousel %}


    {% endblock %}
</div>


<!-- end main -->

<div class="parallax-pro">
    <div class="img-src" style="background-image: url('http://get-shit-done-pro.herokuapp.com/assets/img/bg6.jpg');"></div>
    <div class="container">
        <div class="row">
            <div class="col-md-12 text-center">
                <h1>
                    <small>
                       ¡Ve todo lo que ofrecemos!<a>
                    </small>
                </h1>
            </div>
            <div class="col-md-6 col-md-offset-3 col-md-12 text-center">
                <h1 class="hello text-center">
                   <a href="#XD">ARRIENDOS DE TEMPORADA<span class="label label-warning"> Tour</span></a>
                   <small>
                    <ul class="list-unstyled">
                        <li>Mas de 5 locaciones</li>
                        <li>Cientos de departamentos</li>
                        <li>Servicios extras</li>
                        <li>Descuentos de temporada</li>
                    </ul>
                    </small>
                </h1>
                 <div class="actions">
                     <a class="btn btn-lg btn-warning btn-fill" href="https://www.youtube.com/watch?v=dQw4w9WgXcQ">AGENDA TU HORA</a>
                </div>
            </div>
        </div>
        <div class="space-30"></div>
        <div class="row">
             <div class="col-md-12 text-center">
                <div class="credits">
                    &copy; <script>document.write(new Date().getFullYear())</script> Duoc UC Maipu <a href="#x##d"> Portafolio de titulo </a> 23/09/2021 
                </div>
            </div>
        </div>
    </div>

</div>

</body>

    <script src="{% static '/Turismo_core/jquery/jquery-1.10.2.js' %}" type="text/javascript"></script>
	<script src="{% static '/Turismo_core/assets/js/jquery-ui-1.10.4.custom.min.js' %}" type="text/javascript"></script>

	<script src="{% static '/Turismo_core/bootstrap3/js/bootstrap.js'%}" type="text/javascript"></script>
	<script src="{% static '/Turismo_core/assets/js/gsdk-checkbox.js'%}"></script>
	<script src="{% static '/Turismo_core/assets/js/gsdk-radio.js'%}"></script>
	<script src="{% static '/Turismo_core/assets/js/gsdk-bootstrapswitch.js'%}"></script>
	<script src="{% static '/Turismo_core/assets/js/get-shit-done.js'%}"></script>
    <script src="{% static '/Turismo_core/assets/js/custom.js'%}"></script>

<script type="text/javascript">
         
    $('.btn-tooltip').tooltip();
    $('.label-tooltip').tooltip();
    $('.pick-class-label').click(function(){
        var new_class = $(this).attr('new-class');  
        var old_class = $('#display-buttons').attr('data-class');
        var display_div = $('#display-buttons');
        if(display_div.length) {
        var display_buttons = display_div.find('.btn');
        display_buttons.removeClass(old_class);
        display_buttons.addClass(new_class);
        display_div.attr('data-class', new_class);
        }
    });
    $( "#slider-range" ).slider({
		range: true,
		min: 0,
		max: 500,
		values: [ 75, 300 ],
	});
	$( "#slider-default" ).slider({
			value: 70,
			orientation: "horizontal",
			range: "min",
			animate: true
	});
	$('.carousel').carousel({
      interval: 4000
    });
      
    
</script>
</html>

Turismo_core/templates/Turismo_core/home.html
{% extends 'Turismo_core/base.html'%}

{% block carousel %}
	{% load static %}

    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
        <li data-target="#carousel-example-generic" data-slide-to="1"></li>
        <li data-target="#carousel-example-generic" data-slide-to="2"></li>
      </ol>
    
      <!-- Wrapper for slides -->
      <div class="carousel-inner">
        <div class="item active">
          <img src="{% static 'turismo_core/assets/img/carousel_blue.jpg' %}" alt="Awesome Image">
        </div>
        <div class="item">
          <img src="{% static 'turismo_core/assets/img/carousel_green.png' %}" alt="Awesome Image">
        </div>
        <div class="item">
          <img src="{% static 'turismo_core/assets/img/carousel_red.png' %}" alt="Awesome Image">
        </div>
      </div>
    
      <!-- Controls -->
      <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
        <span class="fa fa-angle-left"></span>
      </a>
      <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
        <span class="fa fa-angle-right"></span>
      </a>
    </div>
</div> <!-- end carousel -->
<div class="main">
    <div class="container tim-container">
        <div id="extras">
            <div class="space"></div>
            <div class="row">
                <div class="col-md-7 col-md-offset-0 col-sm-10 col-sm-offset-1">
                    <div class="text-center">
                        <img src="{% static 'turismo_core/assets/img/dulau.jpg' %}" alt="Rounded Image" class="img-rounded img-responsive img-dog">
                    </div>
                </div>
                <div class="col-md-5 col-sm-12">
                                <h1 class="text-center">ARRIENDOS DE TEMPORADA 
                                
                                <small class="subtitle">Get to know us</small></h1>
                                <hr>
                                <p>
                                Creative Tim offers Bootstrap based design elements that speed up your development work. From plugins to complex kits, we have everything you need. 
                                </p>
                                <p>
                                    We love the web and care deeply for how users interact with a digital product. The idea behind Creative Tim was creating a standard of things we actually need and would personally use inside our web projects. We power businesses and individuals to create better looking web projects around the world.
                                </p>
                                <p>
                                We take great interest in how our customers use our resources and offer strong support and unlimited updates. We are constantly thinking about how to make our products intuitive, beautiful and extremely easy to understand, so feel free to tell us your thoughts!                                   
                                </p>

                </div>
            </div>
        </div>
    <!--     end extras -->    
    </div>
<!-- end container -->
<div class="space-30"></div>

{% endblock%}